filters = [
        ("", "No filter"),
        ("aden", "Aden"),
        ("reyes", "Reyes"),
        ("perpetua", "Perpetua"),
        ("inkwell", "Inkwell"),
        ("toaster", "Toaster"),
        ("walden", "Walden"),
        ("hudson", "Hudson"),
        ("gingham", "Gingham"),
        ("mayfair", "Mayfair"),
        ("lofi", "Lo-fi"),
        ("xpro2", "X-Pro II"),
        ("_1977", "1977"),
        ("brooklyn", "Brooklyn"),
        ("nashville", "Nashville"),
        ("lark", "Lark"),
        ("moon", "Moon"),
        ("clarendon", "Clarendon"),
        ("willow", "Willow")
        ]
