"""empty message

Revision ID: 27a45bf2ef46
Revises: 4855b8b86c3a
Create Date: 2016-07-29 10:09:47.555455

"""

# revision identifiers, used by Alembic.
revision = '27a45bf2ef46'
down_revision = '4855b8b86c3a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battles', sa.Column('challenged_filter', sa.String(length=64), nullable=True))
    op.add_column('battles', sa.Column('challenger_filter', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('battles', 'challenger_filter')
    op.drop_column('battles', 'challenged_filter')
    ### end Alembic commands ###
