"""empty message

Revision ID: 620e37c33d40
Revises: None
Create Date: 2016-07-29 12:18:02.740313

"""

# revision identifiers, used by Alembic.
revision = '620e37c33d40'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('avatar_hash', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_name'), 'images', ['name'], unique=True)
    op.create_table('battles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenger_id', sa.Integer(), nullable=True),
    sa.Column('challenged_id', sa.Integer(), nullable=True),
    sa.Column('challenger_filter', sa.String(length=64), nullable=True),
    sa.Column('challenged_filter', sa.String(length=64), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('challenge_accepted', sa.Boolean(), nullable=True),
    sa.Column('challenger_finished', sa.Boolean(), nullable=True),
    sa.Column('challenged_finished', sa.Boolean(), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['challenged_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['challenger_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battles_challenged_id'), 'battles', ['challenged_id'], unique=False)
    op.create_index(op.f('ix_battles_challenger_id'), 'battles', ['challenger_id'], unique=False)
    op.create_index(op.f('ix_battles_image_id'), 'battles', ['image_id'], unique=False)
    op.create_index(op.f('ix_battles_timestamp'), 'battles', ['timestamp'], unique=False)
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('battle_id', sa.Integer(), nullable=False),
    sa.Column('choice', sa.String(length=16), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['battle_id'], ['battles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'battle_id')
    )
    op.create_index(op.f('ix_votes_timestamp'), 'votes', ['timestamp'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_timestamp'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_battles_timestamp'), table_name='battles')
    op.drop_index(op.f('ix_battles_image_id'), table_name='battles')
    op.drop_index(op.f('ix_battles_challenger_id'), table_name='battles')
    op.drop_index(op.f('ix_battles_challenged_id'), table_name='battles')
    op.drop_table('battles')
    op.drop_index(op.f('ix_images_name'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    op.drop_table('roles')
    ### end Alembic commands ###
